---
platform: linux
image_resource:
  type: docker-image
  source: {repository: maven}


inputs:
- name: pipeline-code
- name: source-code

outputs:
- name: cf-deploy-files

run:
  path: bash
  args: [pipeline-code/concourse/dev/scripts/package.sh]
